list = [
    ("Able - capable", "Ablely - habilement"),
    ("Absent - absent", "Absently - distraitement"),
    ("All - tout, entièrement", "Ally - tout à fait, entièrement"),
    ("Afraid - effrayé", "Afraidly - craintivement"),
    ("Alive - en vie", "Alively - vivement"),
    ("Angry - énervé", "Angrily - énervé"),
    ("Another - un autre","une autre - N/A"),
    ("Asleep - endormi", "Sleepily - endormi"),
    ("Average - moyen", "Averagely - moyennement"),
    ("Away - parti, loin", "Away - loin"),
    ("Back - arrière", "Backward - en arrière"),
    ("Bad - mauvais", "Badly - mal"),
    ("Basic - basique", "Basically - fondamentalement"),
    ("Beautiful - beau", "Beautifully - magnifiquement"),
    ("Best - meilleur, la plus grande partie", "Best - le mieux"),
    ("Big - grand, gros", "Bigly - grandement"),
    ("Bold - audacieux", "Boldly - audacieusement"),
    ("Boring - ennuyeux", "Boringly - ennuyeusement"),
    ("Bright - lumineux, intelligent", "Brightly - brillamment"),
    ("Calm - calme", "Calmly - calmement"),
    ("Careful - prudent", "Carefully - prudemment"),
    ("Cheap - bon marché", "Cheaply - à bas prix"),
    ("Clean - propre", "Cleanly - proprement"),
    ("Close - proche (spatialement et personnellement)", "Closely - étroitement"),
    ("Cloudy - nuageux", "Cloudily - nuageusement"),
    ("Closed - fermé", "Closely - étroitement"),
    ("Cold - froid", "Coldly - froidement"),
    ("Common - commun", "Commonly - communément"),
    ("Confident - confiant", "Confidently - avec assurance"),
    ("Curious - curieux", "Curiously - curieusement"),
    ("Current - courant, actuel", "Currently - actuellement"),
    ("Cute - mignon", "Cutely - mignonnement"),
    ("Dangerous - dangereux", "Dangerously - dangereusement"),
    ("Dark - sombre", "Darkly - sombrement"),
    ("Dead - mort", "Deadly - mortellement"),
    ("Decent - convenable", "Decently - convenablement"),
    ("Different - différent", "Differently - différemment"),
    ("Dirty - sale, corrompu", "Dirtily - malproprement"),
    ("Down - triste, abattu", "Down - en bas"),
    ("Dry - sec", "Dryly - sèchement"),
    ("Due - dû, approprié", "Duly - dûment"),
    ("Dull - ennuyeux, triste, émoussé", "Dully - d'une manière terne"),
    ("Early - précoce, anticipé", "Early - tôt"),
    ("Economic - économique", "Economically - économiquement"),
    ("Economical - économique (pas cher)", "Economically - économiquement"),
    ("Efficient - efficace", "Efficiently - efficacement"),
    ("Exciting - enthousiasmant", "Excitedly - avec enthousiasme"),
    ("Expected - attendu", "Expectedly - comme prévu"),
    ("Expensive - cher", "Expensively - chèrement"),
    ("Even - pair, égal", "Evenly - également"),
    ("Famous - célèbre", "Famously - célèbrement"),
    ("Far - loin, éloigné", "Far - loin"),
    ("Fair - juste, équitable", "Fairly - équitablement"),
    ("Fast - rapide", "Fast - rapidement"),
    ("Fat - gras, gros", "Fattily - gras"),
    ("Financial - financier", "Financially - financièrement"),
    ("Firm - ferme", "Firmly - fermement"),
    ("First - premier", "Firstly - premièrement"),
    ("Foreign - étranger", "Foreignly - étrangement"),
    ("Full - entier", "Fully - entièrement"),
    ("Funny - drôle", "Funnily - de manière amusante"),
    ("Further / farther - plus éloigné, additionnel", "Further / Farther - plus loin"),
    ("Future - futur", "Futuristically - futuriste"),
    ("Former - ancien, précédent", "Formerly - autrefois"),
    ("Free - libre, gratuit", "Freely - librement"),
    ("Friendly - amical", "Friendlily - amicalement"),
    ("General - général", "Generally - généralement"),
    ("Generous - généreux", "Generously - généreusement"),
    ("Genuine - véritable, authentique", "Genuinely - véritablement"),
    ("Good - bon", "Well - bien"),
    ("Great - grand, génial", "Greatly - grandement"),
    ("Guilty - coupable", "Guiltily - coupable"),
    ("Half - demi", "Halfway - à moitié"),
    ("Happy - heureux, joyeux", "Happily - joyeusement"),
    ("Hard - dur, difficile", "Hard - durement"),
    ("Healthy - sain, bon pour la santé", "Healthily - sainement"),
    ("Heavy - lourd", "Heavily - lourdement"),
    ("Helpful - utile", "Helpfully - de manière utile"),
    ("High - grand, haut", "Highly - hautement"),
    ("Hot - chaud, brûlant", "Hotly - chaudement"),
    ("Huge - grand, énorme", "Hugely - énormément"),
    ("Hungry - affamé", "Hungrily - avec faim"),
    ("Important - important", "Importantly - de manière importante"),
    ("Inner - interne, intérieur", "Inwardly - intérieurement"),
    ("Innocent - innocent", "Innocently - innocemment"),
    ("Intelligent - intelligent", "Intelligently - intelligemment"),
    ("Interesting - intéressant", "Interestingly - de manière intéressante"),
    ("Just - juste, équitable", "Justly - justement"),
    ("Kind - gentil", "Kindly - gentiment"),
    ("Large - grand, vaste", "Largely - largement"),
    ("Last - dernier", "Lastly - en dernier lieu"),
    ("Late - en retard, tardif, défunt", "Late - tardivement"),
    ("Later - plus tard, ultérieur", "Later - plus tard"),
    ("Lazy - paresseux", "Lazily - paresseusement"),
    ("Left - à gauche", "Left - à gauche"),
    ("Light - léger, lumineux", "Lightly - légèrement"),
    ("Like - similaire", "Likely - vraisemblablement"),
    ("Likely - probable", "Likely - vraisemblablement"),
    ("Little - petit", "Little - peu"),
    ("Local - local", "Locally - localement"),
    ("Lonely - seul, solitaire", "Lonely - solitairement"),
    ("Long - long", "Long - longuement"),
    ("Loud - fort, bruyant", "Loudly - bruyamment"),
    ("Low - bas", "Low - bassement"),
    ("Lucky - chanceux", "Luckily - heureusement"),
    ("Mad - fou, furieux", "Madly - follement"),
    ("Main - principal", "Mainly - principalement"),
    ("National - national", "Nationally - nationalement"),
    ("Natural - naturel", "Naturally - naturellement"),
    ("Near - proche", "Near - près"),
    ("Nervous - nerveux", "Nervously - nerveusement"),
    ("New - nouveau", "Newly - nouvellement"),
    ("Next - prochain, suivant", "Next - ensuite"),
    ("Nice - bon, sympathique", "Nicely - agréablement"),
    ("Noisy - bruyant", "Noisily - bruyamment"),

    ("Obvious - évident", "Obviously - évidemment"),
    ("Odd - étrange, impair", "Oddly - étrangement"),
    ("Official - officiel", "Officially - officiellement"),
    ("Old - vieux, ancien", "Old - anciennement"),
    ("Only - seul, unique", "Only - seulement"),
    ("Open - ouvert", "Openly - ouvertement"),
    ("Other - autre, différent", "Otherwise - autrement"),
    ("Outer - extérieur", "Outwardly - extérieurement"),
    ("Over - terminé", "Over - par-dessus"),
    ("Own - propre", "Own - proprement"),
    ("Particular - particulier", "Particularly - particulièrement"),
    ("Perfect - parfait", "Perfectly - parfaitement"),
    ("Pleasant - agréable, plaisant", "Pleasantly - agréablement"),
    ("Polite - poli", "Politely - poliment"),
    ("Political - politique", "Politically - politiquement"),
    ("Popular - populaire", "Popularly - populairement"),
    ("Poor - pauvre", "Poorly - mal"),
    ("Possible - possible", "Possibly - possiblement"),
    ("Present - présent", "Presently - actuellement"),
    ("Private - privé", "Privately - en privé"),
    ("Proud - fier", "Proudly - fièrement"),
    ("Public - public", "Publicly - publiquement"),
    ("Pure - pur", "Purely - purement"),
    
    ("Quick - rapide", "Quickly - rapidement"),
    ("Quiet - silencieux", "Quietly - silencieusement"),
    ("Rare - rare", "Rarely - rarement"),
    ("Real - vrai, véritable", "Really - vraiment"),
    ("Reasonable - raisonnable", "Reasonably - raisonnablement"),
    ("Recent - récent", "Recently - récemment"),
    ("Rich - riche", "Richly - richement"),
    ("Right - droit, à droite juste, correct", "Rightly - correctement"),
    ("Round - rond", "Roundly - rondement"),
    ("Running - actuel, coulant", "Runningly - couramment"),
    ("Safe - sûr, en sécurité", "Safely - en toute sécurité"),
    ("Same - même, identique", "Similarly - de manière similaire"),
    ("Scary - effrayant", "Scarily - effrayamment"),
    ("Second - deuxième, second", "Secondly - deuxièmement"),
    ("Selfish - égoïste", "Selfishly - égoïstement"),
    ("Serious - sérieux", "Seriously - sérieusement"),
    ("Sharp - tranchant, perspicace", "Sharply - de manière tranchante, perspicacement"),
    ("Short - court", "Shortly - brièvement"),
    ("Shy - timide", "Shyly - timidement"),
    ("Sick - malade", "Sickly - maladivement"),
    ("Similar - similaire", "Similarly - de manière similaire"),
    ("Slim - mince", "Slimly - mince"),
    ("Slow - lent", "Slowly - lentement"),
    ("Small - petit, peu", "Smally - un petit peu"),
    ("Smart - intelligent, futé", "Smartly - intelligemment, astucieusement"),
    ("Smelly - qui sent fort", "Smellily - de manière malodorante"),
    ("Smooth - lisse", "Smoothly - doucement"),
    ("Soft - doux", "Softly - doucement"),
    ("Special - spécial", "Specially - spécialement"),
    ("Square - carré", "Squarely - carrément"),
    ("Still - calme, immobile", "Still - calmement, immobile"),
    ("Strong - fort", "Strongly - fermement"),
    ("Stupid - stupide", "Stupidly - stupidement"),
    ("Sunny - ensoleillé", "Sunnily - de manière ensoleillée"),
    ("Sure - sûr", "Surely - sûrement"),
    ("Tall - grand", "Tallly - grand"),
    ("Tasty - bon (au goût)", "Tastily - de manière savoureuse"),
    ("Thick - épais (pour une chose)", "Thickly - épaissement"),
    ("Thin - fin", "Thinly - finement"),
    ("Thirsty - assoiffé", "Thirstily - avec soif"),
    ("Tiny - tout petit (minuscule)", "Tinily - de manière minuscule"),
    ("Top - le plus, très bon", "Toply - au mieux"),
    ("Total - total", "Totally - totalement"),
    ("True - vrai", "Truly - véritablement"),
    ("Ugly - laid, moche", "Ugly - de manière laide"),
    ("Unusual - inhabituel", "Unusually - de manière inhabituelle"),
    ("Used - usagé, habitué", "Usually - habituellement"),
    ("Useful - utile", "Usefully - de manière utile"),
    ("Useless - inutile", "Uselessly - inutilement"),
    ("Vague - vague", "Vaguely - vaguement"),
    ("Violent - violent", "Violently - violemment"),
    ("Warm - chaud", "Warmly - chaleureusement"),
    ("Weak - faible", "Weakly - faiblement"),
    ("Weird - bizarre, étrange", "Weirdly - bizarrement"),
    ("Well - bien, en bonne santé", "Well - bien, en bonne santé"),
    ("Wet - humide, mouillé", "Wetly - de manière humide, mouillée"),
    ("Whole - complet", "Wholly - complètement"),
    ("Wild - sauvage", "Wildly - sauvagement"),
    ("Wonderful - merveilleux", "Wonderfully - merveilleusement"),
    ("Working - qui travaille, qui fonctionne", "Workingly - en travaillant, en fonctionnant"),
    ("Wrong - faux, incorrect", "Wrongly - incorrectement"),
    ("Young - jeune", "Youngly - de manière jeune"),
]


english_list = []
french_list = []

for item in list:
    english, french = item[0].split(' - ')
    english2, french2 = item[1].split(' - ')
    english_list.append(f"{english} - {english2}")
    french_list.append(f"{french} - {french2}")

result = []
for i in range(len(english_list)):
        result.append((english_list[i], french_list[i]))
        
for item in result:
    print(f"{item},")
